name: Build (LuaLaTeX)

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build_latex:
    name: Build and log errors
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create build files for cv.tex and cover.tex
      run: |
        echo "::debug::Writing '\def\releasenumber{ga-build}\input{cv}' to cv-build.tex"
        echo '\def\releasenumber{ga-build}\input{cv}' > cv-build.tex
        echo "::debug::Writing '\def\releasenumber{ga-build}\input{cover}' to cover-build.tex"
        echo '\def\releasenumber{ga-build}\input{cover}' > cover-build.tex

    - name: Lint LaTeX documents
      run: |
        docker run --rm -v $(pwd):/workdir ghcr.io/chiefgokhlayeh/textidote:latest --output html cv-build.tex > cv-report.html || echo "Linting failed for cv-build.tex"
        docker run --rm -v $(pwd):/workdir ghcr.io/chiefgokhlayeh/textidote:latest --output html cover-build.tex > cover-report.html || echo "Linting failed for cover-build.tex"

    - name: Upload TeXtidote reports
      uses: actions/upload-artifact@v4
      with:
        name: textidote_reports
        path: |
          cv-report.html
          cover-report.html

    - name: Compile CV LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cv-build.tex
        latexmk_use_lualatex: true

    - name: Compile Cover Letter LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cover-build.tex
        latexmk_use_lualatex: true

    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        path: |
          cv-build.pdf
          cover-build.pdf
        if-no-files-found: error

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        path: |
          cv-build.log
          cover-build.log
