name: Build (LuaLaTeX)

on:
  push:
    branches:
    - main

jobs:
  build_latex:
    name: Build LaTeX documents and log errors
    runs-on: ubuntu-latest

    strategy:
      matrix:
        documents: [ cv, cover ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Compile ${{ matrix.documents }}.tex LaTeX document
      uses: xu-cheng/latex-action@v4
      with:
        root_file: ${{ matrix.documents }}.tex
        latexmk_use_lualatex: true

    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.documents }}.pdf
        path: ${{ matrix.documents }}.pdf
        if-no-files-found: error

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.documents }}.log
        path: ${{ matrix.documents }}.log
