name: Deploy cv.pdf to interactive-resume repository

on:
  push:
    tags:
    - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Checkout cv repository
      uses: actions/checkout@v5

    - name: Compile CV LaTeX document
      uses: xu-cheng/latex-action@v4
      with:
        root_file: cv.tex
        latexmk_use_lualatex: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: cv.pdf

    - name: Checkout interactive-resume repository
      uses: actions/checkout@v5
      with:
        repository: dokson/interactive-resume
        token: ${{ secrets.API_TOKEN_GITHUB }}
        path: interactive-resume

    - name: Copy cv.pdf to interactive-resume document folder
      run: cp -f cv.pdf interactive-resume/document/cv.pdf

    - name: Commit and push to interactive-resume
      uses: cpina/github-action-push-to-another-repository@v1.7.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: interactive-resume
        destination-github-username: dokson
        destination-repository-name: interactive-resume
        user-name: 'github-actions[bot]'
        user-email: 'github-actions[bot]@users.noreply.github.com'
        target-branch: main
        commit-message: '(auto) feat: Update cv.pdf from dokson/cv latest release ${{ steps.get_version.outputs.VERSION }}'
