name: Publish PDF release to website

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ dispatch_publish ]

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    steps:
    - name: Get the release
      uses: pozetroninc/github-action-get-latest-release@master
      id: cv_release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'dokson/cv'

    - name: Echo release tag name
      run: echo "::debug::Found tag for LATEST release >> ${{ steps.cv_release.outputs.release }}"

    - name: Download cv.pdf from release
      uses: robinraju/release-downloader@v1.12
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'dokson/cv'
        tag: ${{ steps.cv_release.outputs.release }}
        out-file-path: './cv-download'
        fileName: 'cv.pdf'

    - name: Checkout interactive-resume repository
      uses: actions/checkout@v4
      with:
        repository: dokson/interactive-resume
        token: ${{ secrets.API_TOKEN_GITHUB }}
        path: './interactive-resume'

    - name: Copy updated cv.pdf to interactive-resume
      run: |
        cp -f ./cv-download/cv.pdf ./interactive-resume/document/cv.pdf

    - name: Commit and push changes to dokson/interactive-resume repository
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'interactive-resume-repo'
        destination-github-username: 'dokson'
        destination-repository-name: 'interactive-resume'
        user-email: ale.colace@gmail.com
        target-branch: master
        commit-message: 'Updates from cv release ${{ steps.cv_release.outputs.release }}'
